"""create initial tables

Revision ID: adaf09a759e6
Revises: 
Create Date: 2025-07-28 15:14:38.575271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adaf09a759e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_criaturas_nome'), table_name='criaturas')
    op.drop_index(op.f('ix_criaturas_regiao'), table_name='criaturas')
    op.drop_table('criaturas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criaturas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('regiao', sa.VARCHAR(length=20), nullable=False),
    sa.Column('periculosidade', sa.INTEGER(), nullable=False),
    sa.Column('lenda', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criaturas_regiao'), 'criaturas', ['regiao'], unique=False)
    op.create_index(op.f('ix_criaturas_nome'), 'criaturas', ['nome'], unique=1)
    # ### end Alembic commands ###
